# Start with the name of Allah who is the most Benefical and most Mercifull

# Topic: Mathematical & Statistical Method

# mean(): Returns the mean value computed over the array

# cumsum(): Returns the Cumulative sum of array element

# cumprod(): Returns the Cumulative product of array element 

# any, all , sorting,unique,sum. these all methods are avalible in numpy 

In [8]:
import numpy as np

In [9]:
x = np.array([2,1,5,8,9])

In [11]:
x.mean()

5.0

In [12]:
x.cumsum()

array([ 2,  3,  8, 16, 25], dtype=int32)

In [13]:
x.cumprod()

array([  2,   2,  10,  80, 720], dtype=int32)

In [14]:
y = x>6

In [15]:
y

array([False, False, False,  True,  True])

In [16]:
y.sum()

2

In [17]:
y.any()

True

In [18]:
y.all()

False

In [19]:
x

array([2, 1, 5, 8, 9])

In [20]:
x.sort()

In [21]:
x

array([1, 2, 5, 8, 9])

In [22]:
np.unique(x)

array([1, 2, 5, 8, 9])