# Start with the name of Allah who is the most Benefical and most Mercifull

# Topic: Linear Algebra Functions

In [1]:
import numpy as np

In [2]:
x = np.random.randn(2,3)

In [3]:
y = np.random.randn(3,2)

In [4]:
x.dot(y)

array([[-0.14729477,  1.48999856],
       [-1.26985829,  1.38066281]])

In [5]:
x

array([[-0.52940154, -0.57903654,  1.33567429],
       [ 0.91603071, -0.97953393,  1.04770949]])

In [6]:
y

array([[-0.87752291, -0.22574727],
       [-0.02650327, -0.97544842],
       [-0.46957789,  0.60319147]])

In [7]:
x.transpose()

array([[-0.52940154,  0.91603071],
       [-0.57903654, -0.97953393],
       [ 1.33567429,  1.04770949]])

In [8]:
x.trace()

-1.508935467079239