# start with the name of Allah most benefical and most Mercifull

# Topic: Indexing & Slicing

# Acts Similar as python list

# Boolean Indexing: Specifying Boolean Arrays as index

# Fancy Indexing: Sspecifying Arbitary Arrays as Indexes

# Slicing: Array Slicies are views on the orignal way

In [1]:
import numpy as np

In [2]:
x = np.array([2,3,4,5,6])

In [3]:
x[4]

6

In [4]:
x>5

array([False, False, False, False,  True])

In [5]:
x[x>5]

array([6])

In [6]:
x[[4,1]]

array([6, 3])

In [8]:
y = np.random.randn(10,10)

In [9]:
y

array([[ 0.26354623, -0.21376075,  1.01685798,  0.14042974,  0.69888751,
        -0.84789475,  1.987109  ,  1.01659388,  0.9615795 ,  0.62329579],
       [-1.81581044,  1.48913145,  1.26343723,  1.40533814,  0.32510388,
         0.02614948, -1.56349387,  0.23446643,  1.07623773,  0.82918481],
       [ 0.51361714, -0.12809879, -0.7038037 ,  1.22146548, -1.510688  ,
         1.99899841,  0.89059547, -0.12459265,  0.12984315, -0.47307698],
       [-0.1331285 ,  0.19153853,  1.74368779,  1.53853664,  0.47900223,
        -0.50479836, -1.42205153, -0.60042422, -1.12267381, -0.75291789],
       [-0.63482488, -1.62897295, -1.25280921,  0.56777443,  0.85615446,
        -0.75444469,  0.63906795, -0.35526556, -0.98277516,  1.19230226],
       [ 0.08407748, -1.02546179,  0.38420986,  0.48714747, -0.10107977,
         2.74079544, -1.15752534, -1.50582336,  1.95708117, -0.22127395],
       [-0.69279658, -0.9273858 , -0.47205012,  1.09749506, -0.88085004,
        -0.84841198,  1.60257757,  0.91456793

In [13]:
y[1][4]

0.32510387683067077

In [14]:
y[1:10:2]

array([[-1.81581044,  1.48913145,  1.26343723,  1.40533814,  0.32510388,
         0.02614948, -1.56349387,  0.23446643,  1.07623773,  0.82918481],
       [-0.1331285 ,  0.19153853,  1.74368779,  1.53853664,  0.47900223,
        -0.50479836, -1.42205153, -0.60042422, -1.12267381, -0.75291789],
       [ 0.08407748, -1.02546179,  0.38420986,  0.48714747, -0.10107977,
         2.74079544, -1.15752534, -1.50582336,  1.95708117, -0.22127395],
       [ 0.42246324,  1.97931183,  0.51704088, -1.29001373,  0.50862165,
         0.95988471,  0.46212917,  0.72879176, -0.64043062, -1.22222915],
       [ 0.93170813,  1.54034468, -2.06711112,  0.53285453,  0.1857541 ,
         0.23174844, -0.47425653,  1.17109474, -0.88064403,  2.83260796]])

In [25]:
a = np.ones((6,4))

In [26]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
a[1:-1,1:-1]=0

In [28]:
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])