# Start with the name of Allah who is the most benefical and most Mercifull

# TOPIC: A Multi Dimensional Array Object

# A fast Flexible container for large datasets in python


# Homogeneous Data : All of the elements must be same type

In [1]:
import numpy as np

In [2]:
x =np.zeros((3,2))

In [3]:
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
np.ones((2,2),dtype=float)

array([[1., 1.],
       [1., 1.]])

In [5]:
np.empty((2,3))    #not everytime its returns 0 its returns a number as well

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#convert a list into numpy array
list1 = [2,3,4,5,6]
np.array(list1)


array([2, 3, 4, 5, 6])

In [7]:
x = np.arange(1,101,10)

In [8]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
x.shape

(10,)

In [11]:
p=np.zeros((10,10))

In [12]:
p.shape

(10, 10)

In [15]:
y = p.reshape(2,2,5,5)

In [16]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [17]:
y.dtype

dtype('float64')

In [18]:
y.ndim

4