# Start with the name of Allah who is the most benfical and most mercifull

# TOPIC: Arithematic with ndarray as Vectorized Operations

# 1. Express batch operations on data without writing any for loop



# 2. Any Arithematic operations between equal size array applies the operation element wise

# 3. Arithemaics operations with scalars propogate the scalar argument to each element in the array

In [1]:
import numpy as np

In [2]:
#add two arrays 
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [5]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [7]:
arr2 = np.array([ [3,4,5],[6,7,8] ])
arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [8]:
arr2>arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr2<arr

array([[False, False, False],
       [False, False, False]])

In [10]:
#jis index par value true hai wo value utha kar lai aia hai
arr[arr>0]

array([1, 2, 3, 4, 5, 6])