# Start with the name of Allah most Benefical and most Mercifull

# Topic: Element Wise Array Function

In [1]:
import numpy as np

In [2]:
x = np.array([3,2,7,8,9])

In [3]:
np.sqrt(x)

array([1.73205081, 1.41421356, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.power(x,3)

array([ 27,   8, 343, 512, 729], dtype=int32)

In [5]:
y = [10,1,5,9,10]

In [6]:
np.maximum(x,y)

array([10,  2,  7,  9, 10])