# Start with the name of Allah who is the most Benefical and most Mercifull

# Topic: Reshape

In [1]:
import numpy as np

In [2]:
x =np.random.randn(4,5)

In [3]:
x

array([[ 0.07503591,  1.83405508, -1.57534776,  0.9627509 , -0.6332034 ],
       [-0.61995754,  0.47012465,  0.37609337,  1.39749294, -1.30409074],
       [-0.17695078,  0.12251383, -0.58891068, -1.36607618, -0.27182862],
       [ 0.76966685,  0.41078715,  0.33701605, -0.69072571,  0.49930658]])

In [4]:
x.reshape(2,2,5)

array([[[ 0.07503591,  1.83405508, -1.57534776,  0.9627509 ,
         -0.6332034 ],
        [-0.61995754,  0.47012465,  0.37609337,  1.39749294,
         -1.30409074]],

       [[-0.17695078,  0.12251383, -0.58891068, -1.36607618,
         -0.27182862],
        [ 0.76966685,  0.41078715,  0.33701605, -0.69072571,
          0.49930658]]])

In [5]:
x.reshape((2,2,5),order="F")

array([[[ 0.07503591,  1.83405508, -1.57534776,  0.9627509 ,
         -0.6332034 ],
        [-0.17695078,  0.12251383, -0.58891068, -1.36607618,
         -0.27182862]],

       [[-0.61995754,  0.47012465,  0.37609337,  1.39749294,
         -1.30409074],
        [ 0.76966685,  0.41078715,  0.33701605, -0.69072571,
          0.49930658]]])

In [6]:
x.reshape((2,2,-1))

array([[[ 0.07503591,  1.83405508, -1.57534776,  0.9627509 ,
         -0.6332034 ],
        [-0.61995754,  0.47012465,  0.37609337,  1.39749294,
         -1.30409074]],

       [[-0.17695078,  0.12251383, -0.58891068, -1.36607618,
         -0.27182862],
        [ 0.76966685,  0.41078715,  0.33701605, -0.69072571,
          0.49930658]]])

In [7]:
x

array([[ 0.07503591,  1.83405508, -1.57534776,  0.9627509 , -0.6332034 ],
       [-0.61995754,  0.47012465,  0.37609337,  1.39749294, -1.30409074],
       [-0.17695078,  0.12251383, -0.58891068, -1.36607618, -0.27182862],
       [ 0.76966685,  0.41078715,  0.33701605, -0.69072571,  0.49930658]])

In [8]:
x.ravel()

array([ 0.07503591,  1.83405508, -1.57534776,  0.9627509 , -0.6332034 ,
       -0.61995754,  0.47012465,  0.37609337,  1.39749294, -1.30409074,
       -0.17695078,  0.12251383, -0.58891068, -1.36607618, -0.27182862,
        0.76966685,  0.41078715,  0.33701605, -0.69072571,  0.49930658])

In [9]:
x.flatten()

array([ 0.07503591,  1.83405508, -1.57534776,  0.9627509 , -0.6332034 ,
       -0.61995754,  0.47012465,  0.37609337,  1.39749294, -1.30409074,
       -0.17695078,  0.12251383, -0.58891068, -1.36607618, -0.27182862,
        0.76966685,  0.41078715,  0.33701605, -0.69072571,  0.49930658])